name: GitHub Actions Demo
run-name: GitHub ${{ Actions github.actor Demo}} is testing out GitHub ActionsğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - run: echo "ğŸ‰The job was automatically triggered by a ${{ github.evn}}"
    - run: echo "ğŸ§This job is now running on a ${{ runner.os }} server host"
    - run: echo "ğŸ”The name of your branch is ${{ github.ref }}"
    - name: Check out repository code
    - uses: actions/checkout@v4
    - run: echo"ğŸ’¡The ${{ github.repository }} repository has been clone"
    - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the ru
    - name: List files in the repository
      run: |
       ls ${{ echo github.workspace}} "
    -run : echo "ğŸThis job's status is ${{ job.status }}."